[package]
name = "orbit-core"
description = "Core of Orbit"
edition.workspace = true
version.workspace = true
authors.workspace = true
license-file.workspace = true

[lib]
path = "lib.rs"

[lints]
workspace = true
